configfile = "config/config.yaml"

def input_all(wc):
    for runid in config["runs"]:
        yield "results/nanoplot/{runid}"

rule all:
    input: input_all

def input_nanoplot(wc):
        f"config['prefix']{wc.runid}/no_sample/config['runs'][wc.runid]['dirname']/config['runs'][wc.runid]['summary']"

rule nanoplot:
	input: input_nanoplot
    output:
        d=directory("results/nanoplot/{runid}"),
	conda: "envs/nanoplot.yaml"
    log:
        o="log/nanoplot/{runid}.log",
        e="log/nanoplot/{runid}.err"
    benchmark: "log/nanoplot/{runid}.bmk"
    threads: 8
    resources:
        mem_mb=64000,
        runtime=120
	shell: """
        NanoPlot --summary {input.summary} -o {output.d} > {log.o} 2> {log.e}
    """
